import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/common/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${inter.className} relative bg-background min-h-screen text-fg w-full max-w-screen overflow-x-hidden`}>
        <div className="main-gradient absolute h-full w-full left-0 top-0" />
        <Navbar />
        <main className="relative z-10 container mx-auto">
          {children}
        </main>
      </body>
    </html>
  );
}
